Comments 1
EshaanAgg/LFXMM-Backend pull request #1
Opened 2023-09-26 07:13 UTC by SomeYoGuyeee

Comments added to GetAllOrgs.go, client.go and parentOrg.go

2023-09-26 08:31 UTC, EshaanAgg requested changes

2023-09-26 08:31 UTC, EshaanAgg commented on database/handlers/parentOrg.go
> +	orgs, err := parseResultSetToSlice(rowsRs) // this fn is defined below
Either use `function` or `func`.

2023-09-26 09:16 UTC, EshaanAgg commented
You can just add new commits to this branch itself, they will be updated in this PR automatically :)

2023-09-26 09:44 UTC, SomeYoGuyeee commented
Ok bhaiya, try karta hu

2023-09-26 09:49 UTC, SomeYoGuyeee commented
I've made the commits bhaiya

2023-09-26 09:51 UTC, EshaanAgg commented on database/handlers/client.go
> + * returns: client (database) object
Capitalize `R`

2023-09-26 10:06 UTC, SomeYoGuyeee commented on database/handlers/client.go
> + * returns: client (database) object
Done bhaiya

2023-09-27 05:47 UTC, EshaanAgg approved these changes
LGTM @SomeYoGuyeee! Good work.

2023-09-27 05:48 UTC, merged