All Projects Route Created
EshaanAgg/LFXMM-Backend pull request #18
Opened 2023-10-05 14:29 UTC by Vishalk91-4

Partially Fixes issue #3

Created **getAllProjects go** file, so as to fetch all projects and display them, this is a subpart of **search bar**, which will be used to search both orgs or projects directly

![image](https://github.com/EshaanAgg/LFXMM-Backend/assets/116670999/ec6968e1-c742-462b-bff5-f37af608c067)

@EshaanAgg could you please review this pull request

2023-10-05 15:34 UTC, EshaanAgg requested changes
@Vishalk91-4 The PR looks good, but there is no real need for this right now. Instead, I would advise you to change this endpoint to accept a query parameter called `filterText`, and then this endpoint returns all the projects whose name or description matches the same. Then this endpoint could be used in the frontend directly, and we wouldn't require searching on frontend.

2023-10-08 09:51 UTC, Vishalk91-4 commented
@EshaanAgg, could you please review it
I just checked that main.go has filtering of projects by year also, do we have to keep it separate

2023-10-09 03:54 UTC, EshaanAgg commented
@Vishalk91-4 Good job, and the PR now performs filtering. But instead of creating a new endpoint, it would be better to change the `/projects` endpoint to accept an optional query parameter called `filterText`. If the same is provided, then we use the `like` query, else if the same is not provided or is `""`, we provide all the organizations. It should be an easy fix. 

We will keep by-year filtering separate as it is being used in the graph component for UI.

2023-10-11 03:52 UTC, Vishalk91-4 commented
@EshaanAgg, I've added a commit, could you check

2023-10-11 05:05 UTC, EshaanAgg requested changes
Need some changes.

2023-10-11 05:05 UTC, EshaanAgg commented on api/getProjectsByFilter.go
> +
Remove extra newline.

2023-10-11 05:05 UTC, EshaanAgg commented on api/getProjectsByFilter.go
> +
Remove extra newline.

2023-10-11 05:05 UTC, EshaanAgg commented on database/handlers/project.go
> +	rowsRs, err := client.Query("SELECT id, name, description, programYear, programTerm FROM projects WHERE name LIKE '%' || $1 OR description LIKE '%' || $1;", filterText)
Can't understand the like clauses in this query. Shouldn't it be like `name LIKE '%$1%' OR description LIKE '%$1$'`?

2023-10-11 08:00 UTC, Vishalk91-4 commented on api/getProjectsByFilter.go
> +
Removed

2023-10-12 05:13 UTC, merged